In [1]:
import numpy as np

In [6]:
arr = np.array([1,2])
print(arr)
print()
two_array = np.array([[1,2],[3,4]])
print("2D-Array")
print(two_array)

[1 2]

2D-Array
[[1 2]
 [3 4]]


In [4]:
type(arr)
type(two_array)

numpy.ndarray

In [8]:
print(arr.size)
print(two_array.size)

2
4


In [9]:
print(arr.shape)
print(two_array.shape)

(2,)
(2, 2)


In [10]:
print(arr.dtype)
print(two_array.dtype)


int32
int32


arr.transpose() will transpose the array(same as matrix)

In [8]:
two_array.transpose()

array([[1, 3],
       [2, 4]])

np.empty((row,col),dtype) will generate a random array of size row col containing elements
of "dtype"

In [9]:
np.empty((5,5),dtype = int)

array([[-1552763896,         649,          64,           0,           0],
       [          0,           0,           0,           0,     6881382],
       [ 1650537264,   875638838,  1701197110,   825833780,  1667446583],
       [ 1701012835,   811754342,   876098148,   925906485,   811940152],
       [ 1717909606,   862216503,   811939122,  1717842533,   945895730]])

In [11]:
np.empty((4,4),dtype = int)

array([[      0,       0,       0,       0],
       [      0,       0,       0,       0],
       [      0,       0,    1036,       0],
       [      0, 7602273,       0, 7274572]])

np.ones((row, col), dtype) will generate an array of size row col containing "1's" of "dtype"

Ways to write:

np.ones(col)--> Generate "col" numebr of 1's of type float ("1.")

np.ones((row,col))-> Generate "1." of row col

np.ones((row.col), dtype)

In [23]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones((4,4),dtype = bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

np.zeros((row,col),dtype)(everything same as ones())

In [13]:
np.zeros((5,5),dtype = str)

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

np.arange(start,end ,steps).Default steps =1

In [19]:
np.arange(3,20,3)

array([ 3,  6,  9, 12, 15, 18])

reshape((rows,cols))reshape array to x*y

In [11]:
arr = np.arange(0,9).reshape((3,3))

In [12]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Array Slicing in numpy

In [27]:
arr = np.arange(1,51)
arr = arr.reshape(10,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

arr[row] will be return

In [28]:
arr[0]

array([1, 2, 3, 4, 5])

In [29]:
arr[0,0]

1

We can also use arr[row1:row2,col1:col2] same as slicig in python 

In [31]:
arr.argmax()

49

np.sum(arr) returns sum of arr np.sum(arr, axis = 1)returns sum of every row np.sum(arr,axix = 0)return sum of every col

In [32]:
np.sum(arr)

1275

In [34]:
np.sum(arr, axis =1)

array([ 15,  40,  65,  90, 115, 140, 165, 190, 215, 240])

In [37]:
np.sum(arr, axis =0)

array([235, 245, 255, 265, 275])

Add,Multiply, subtract of array

In [36]:
import numpy as np
var = np.array([1,2,3,4])
var1 = np.array([4,5,6,8])
var2 = var + var1
print(var2)
var3 = var* var1
print(var3)
var4 = np.subtract(var,var1)
print(var4)

[ 5  7  9 12]
[ 4 10 18 32]
[-3 -3 -3 -4]


In [38]:
#shuffle
import numpy as np
a = np.array([1,2,3,4,6,7])
np.random.shuffle(a)

print(a)

[7 6 3 2 4 1]


In [39]:
#resize
import numpy as np
a = np.array([1,2,3,4,6,7])
x = np.resize(a,(3,2))

print(x)

[[1 2]
 [3 4]
 [6 7]]
